[General]
color=#FF2E88
current-version=0.6.0
detect-codes=true
detect-text=true
has-screenshot-permission=true
language=deu, eng, ita
last-update-check=0
mode=parse
notification=false
parse-text=true
show-introduction=false
tray=false
update=false
version=false
